REQUIRED_COLUMNS = {
    "PROCESAMIENTO": [
        "ENTIDAD", "FACTURA", "TIPO_REGISTRO", "FECHA_SERVICIO_TRANSPORTE", "FECHA_PROCESAMIENTO",
        "IDENTIFICACION_CLIENTE", "RAZON_SOCIAL", "CODIGO_PUNTO_CARGO", "NOMBRE_PUNTO_CARGO",
        "CODIGO_CIIU_FONDO", "CIUDAD_FONDO", "NOMBRE_TIPO_SERVICIO", "MONEDA_DIVISA",
        "VALOR_PROCESADO_BILLETE", "VALOR_PROCESADO_MONEDA", "VALOR_TOTAL_PROCESADO",
        "FACTOR_DE_LIQUIDACION", "BASE_DE_LIQUIDACION", "TARIFA", "COSTO_SUBTOTAL", "PORCENTAJE_AIU",
        "IVA", "VALOR_TOTAL"
    ],
    "TRANSPORTE": [
        "ENTIDAD", "FACTURA", "TIPO_REGISTRO", "FECHA_SERVICIO_TRANSPORTE", "IDENTIFICACION_CLIENTE",
        "RAZON_SOCIAL", "CODIGO_PUNTO_CARGO", "NOMBRE_PUNTO_CARGO", "CODIGO_CIIU_PUNTO",
        "CIUDAD_MUNICIPIO_PUNTO", "CODIGO_CIIU_FONDO", "CIUDAD_FONDO", "NOMBRE_TIPO_SERVICIO",
        "TIPO_PEDIDO", "ESCALA", "EXCLUSIVO_MONEDA", "MONEDA_DIVISA",
        "VALOR_TRANSPORTADO_BILLETE_PESOS", "VALOR_TRANSPORTADO_MONEDA_PESOS", "VALOR_TOTAL_TRANSPORTADO_PESOS",
        "NUMERO_FAJOS", "NUMERO_DE_BOLSAS_MONEDA", "COSTO_FIJO", "COSTO_POR_MILAJE", "COSTO_POR_BOLSA",
        "COSTO_FLETES", "COSTO_EMISARIOS", "OTROS_1", "OTROS_2", "OTROS_3", "OTROS_4", "OTROS_5",
        "SUBTOTAL", "PORCENTAJE_AIU", "IVA", "VALOR_TOTAL"
    ]
}

OPTIONAL_COLUMNS = {
    "PROCESAMIENTO": ["TRM_CONVERSION", "PORCENTAJE_IVA", "OBSERVACIONES_ATH", "OBSERVACIONES_TDV"],
    "TRANSPORTE": ["TRM_CONVERSION", "PORCENTAJE_IVA"]
}

EXPECTED_COLUMNS = {
    hoja: REQUIRED_COLUMNS[hoja] + OPTIONAL_COLUMNS.get(hoja, [])
    for hoja in REQUIRED_COLUMNS
}