REQUIRED_COLUMNS = {
    "PROCESAMIENTO": [
        "ENTIDAD", "FACTURA", "TIPO_REGISTRO", "FECHA_SERVICIO_TRANSPORTE", "FECHA_PROCESAMIENTO",
        "IDENTIFICACION_CLIENTE", "RAZON_SOCIAL_CLIENTE", "CODIGO_PUNTO", "NOMBRE_PUNTO",
        "CODIGO_CIUDAD_PUNTO", "NOMBRE_CIUDAD_PUNTO", "TIPO_SERVICIO", "MONEDA_DIVISA",
        "VALOR_PROCESADO_BILLETE", "VALOR_PROCESADO_MONEDA", "VALOR_TOTAL_PROCESADO",
        "FACTOR_LIQUIDACION", "BASE_LIQUIDACION", "TARIFA", "SUBTOTAL", "PORCENTAJE_AIU",
        "IVA", "TOTAL"
    ],
    "TRANSPORTE": [
        "ENTIDAD", "FACTURA", "TIPO_REGISTRO", "FECHA_SERVICIO", "IDENTIFICACION_CLIENTE",
        "RAZON_SOCIAL_CLIENTE", "CODIGO_PUNTO", "NOMBRE_PUNTO", "CODIGO_CIUDAD_PUNTO",
        "NOMBRE_CIUDAD_PUNTO", "CODIGO_CIUDAD_FONDO", "NOMBRE_CIUDAD_FONDO", "TIPO_SERVICIO",
        "TIPO_PEDIDO", "ESCALA", "EXCLUSIVO_MONEDA", "MONEDA_DIVISA",
        "VALOR_TRANSPORTADO_BILLETE", "VALOR_TRANSPORTADO_MONEDA", "VALOR_TOTAL_TRANSPORTADO",
        "NUMERO_FAJO", "NUMERO_DE_BOLSAS_MONEDA", "COSTO_FIJO", "COSTO_POR_MILAJE", "COSTO_POR_BOLSA",
        "COSTO_FLETES", "COSTO_EMISARIOS", "OTROS_1", "OTROS_2", "OTROS_3", "OTROS_4", "OTROS_5",
        "SUBTOTAL", "PORCENTAJE_AIU", "IVA", "TOTAL"
    ]
}

OPTIONAL_COLUMNS = {
    "PROCESAMIENTO": ["TRM_CONVERSION", "PORCENTAJE_IVA", "OBSERVACIONES_ATH", "OBSERVACIONES_TDV"],
    "TRANSPORTE": ["TRM_CONVERSION", "PORCENTAJE_IVA"]
}

EXPECTED_COLUMNS = {
    hoja: REQUIRED_COLUMNS[hoja] + OPTIONAL_COLUMNS.get(hoja, [])
    for hoja in REQUIRED_COLUMNS
}