TIPOS_COLUMNAS = {
    "PROCESAMIENTO": {
        "FECHA_SERVICIO_TRANSPORTE": "fecha",
        "FECHA_PROCESAMIENTO": "fecha",
        "IDENTIFICACION_CLIENTE": "numerico",
        "CODIGO_CIUDAD_PUNTO": "numerico",
        "TRM_CONVERSION": "decimal2",
        "VALOR_PROCESADO_BILLETE": "decimal2",
        "VALOR_PROCESADO_MONEDA": "decimal2",
        "VALOR_TOTAL_PROCESADO": "decimal2",
        "BASE_LIQUIDACION": "decimal4",
        "TARIFA": "decimal4",
        "SUBTOTAL": "decimal4",
        "PORCENTAJE_AIU": "porcentaje",
        "PORCENTAJE_IVA": "porcentaje",
        "IVA": "decimal4",
        "TOTAL": "decimal4",
    },
    "TRANSPORTE": {
        "FECHA_SERVICIO": "fecha",
        "IDENTIFICACION_CLIENTE": "numerico",
        "CODIGO_CIUDAD_PUNTO": "numerico",
        "CODIGO_FONDO": "numerico",
        "CODIGO_CIUDAD_FONDO" : "numerico",
        "TRM_CONVERSION": "decimal2",
        "VALOR_TRANSPORTADO_BILLETE": "decimal2",
        "VALOR_TRANSPORTADO_MONEDA": "decimal2",
        "VALOR_TOTAL_TRANSPORTADO": "decimal2",
        "NUMERO_FAJO": "decimal2",
        "NUMERO_DE_BOLSAS_MONEDA": "decimal2",
        "COSTO_FIJO": "numerico",
        "COSTO_POR_MILAJE": "decimal4",
        "COSTO_POR_BOLSA": "decimal4",
        "COSTO_FLETES": "numerico",
        "COSTO_EMISARIOS": "numerico",
        "OTROS_1": "numerico",
        "OTROS_2": "numerico",
        "OTROS_3": "numerico",
        "OTROS_4": "numerico",
        "OTROS_5": "numerico",
        "SUBTOTAL": "decimal4",
        "PORCENTAJE_AIU": "porcentaje",
        "PORCENTAJE_IVA": "porcentaje",
        "IVA": "decimal4",
        "TOTAL": "decimal4",
    }
}