TIPOS_COLUMNAS = {
    "PROCESAMIENTO": {
        "FECHA_SERVICIO_TRANSPORTE": "fecha",
        "FECHA_PROCESAMIENTO": "fecha",
        "IDENTIFICACION_CLIENTE": "numerico",
        "CODIGO_CIIU_FONDO": "numerico",
        "TRM_CONVERSION": "decimal2",
        "VALOR_PROCESADO_BILLETE": "decimal2",
        "VALOR_PROCESADO_MONEDA": "decimal2",
        "VALOR_TOTAL_PROCESADO": "decimal2",
        "BASE_DE_LIQUIDACION": "decimal4",
        "TARIFA": "decimal4",
        "COSTO_SUBTOTAL": "decimal4",
        "PORCENTAJE_AIU": "porcentaje",
        "PORCENTAJE_IVA": "porcentaje",
        "IVA": "decimal4",
        "VALOR_TOTAL": "decimal4",
    },
    "TRANSPORTE": {
        "FECHA_SERVICIO_TRANSPORTE": "fecha",
        "IDENTIFICACION_CLIENTE": "numerico",
        "CODIGO_CIIU_PUNTO": "numerico",
        "CODIGO_FONDO": "numerico",
        "CODIGO_CIIU_FONDO" : "numerico",
        "TRM_CONVERSION": "decimal2",
        "VALOR_TRANSPORTADO_BILLETE_PESOS": "decimal2",
        "VALOR_TRANSPORTADO_MONEDA_PESOS": "decimal2",
        "VALOR_TOTAL_TRANSPORTADO_PESOS": "decimal2",
        "NUMERO_FAJOS": "decimal2",
        "NUMERO_DE_BOLSAS_MONEDA": "decimal2",
        "COSTO_FIJO": "numerico",
        "COSTO_POR_MILAJE": "decimal4",
        "COSTO_POR_BOLSA": "decimal4",
        "COSTO_FLETES": "numerico",
        "COSTO_EMISARIOS": "numerico",
        "OTROS_1": "numerico",
        "OTROS_2": "numerico",
        "OTROS_3": "numerico",
        "OTROS_4": "numerico",
        "OTROS_5": "numerico",
        "SUBTOTAL": "decimal4",
        "PORCENTAJE_AIU": "porcentaje",
        "PORCENTAJE_IVA": "porcentaje",
        "IVA": "decimal4",
        "VALOR_TOTAL": "decimal4",
    }
}